version: "3.8"

services:

  vpn-portal-backend:
    image: ${DOCKERHUB_USERNAME}/vpn-portal-backend:latest
    environment:
      LDAP_URL: ldap://lldap:3890
      LDAP_BASE: dc=clsma,dc=com,dc=co
      LDAP_BIND_DN: uid=admin,ou=people,dc=clsma,dc=com,dc=co
      LDAP_BIND_PASSWORD: ${LLDAP_ADMIN_PASSWORD}
      OVPN_CLIENTS_PATH: /opt/services/auth/vpn/clients
      OPENVPN_VOLUME: /opt/services/auth/vpn
      OPENVPN_IMAGE: kylemanna/openvpn
      CORS_ORIGINS: https://vpn.clsma.com.co
    volumes:
      - /opt/services/auth/vpn:/opt/services/auth/vpn
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - identity_network
      - dokploy-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=false"

  vpn-portal-frontend:
    image: ${DOCKERHUB_USERNAME}/vpn-portal-frontend:latest
    networks:
      - dokploy-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  identity_network:
    external: true
  dokploy-network:
    external: true
